### ISSUE TITLE
error   no attribute 'find_all'

### ISSUE THREAD

**Issue by vishal-y** [abhi-shek2000/Rotating_IP#1]
Traceback (most recent call last):
  File "c:\Users\heyia\vishal code\PYTHON\change_ip.py", line 22, in <module>
    get_free_proxies()
  File "c:\Users\heyia\vishal code\PYTHON\change_ip.py", line 11, in get_free_proxies
    vs = soup.find("table", attrs={"id": "proxylisttable"}).find_all("tr")[1:]
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by abhi-shek2000** [comment]
This issue is solved
